sudo: required
services:
  - docker
before_install:
  - docker build -t dohungthinhtin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dohungthinhtin/react-test npm test -- --coverage

after_success:
  - docker build -t dohungthinhtin/multi-client ./client
  - docker build -t dohungthinhtin/multi-nginx ./nginx
  - docker build -t dohungthinhtin/multi-server ./server
  - docker build -t dohungthinhtin/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dohungthinhtin/multi-client
  - docker push dohungthinhtin/multi-nginx
  - docker push dohungthinhtin/multi-server
  - docker push dohungthinhtin/multi-worker
